version: "3.7"
services:
  mediapipe:
    build:
      context: .
    shm_size: '2gb'
    environment:
      - INTERNAL_API_TOKEN=32aa1e16-3d91-435a-897b-5aaa740b18ad
      - NVIDIA_VISIBLE_DEVICES=3
      - DEPLOY_PATH=/api
    devices:
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
      - /dev/nvidia3:/dev/nvidia3
      - /dev/nvidiactl:/dev/nvidiactl
    volumes:
      - /home/forge/video:/mediapipe/server/static/video
    networks:
      - external
    ports:
      - 127.0.0.1:5000:8888

networks:
  external:
